print("구구단")
a =int(input("구하고자 하는값 :"))
print (f"{a} X 2 = {a*2}")
print (f"{a} X 3 = {a*3}")
print (f"{a} X 4 = {a*4}")
print (f"{a} X 5 = {a*5}")
print (f"{a} X 6 = {a*6}")
print (f"{a} X 7 = {a*7}")
print (f"{a} X 8 = {a*8}")
print (f"{a} X 9 = {a*9}")